### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/vets-website#11229]
## User Story:
As a Front End Developer, I need to implement Google Analytics for our product's websites so that I can track stats about our users.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [ ] Meet with GA team once websites are set up - 1 hour - Owner
- [ ] Implement GA scripts on websites - y hour(s) - Owner

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
- [ ] See user stats on Google Tag Manager
