### ISSUE TITLE
MDT-Form-2346 Set up Schemas

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/vets-website#11709]
## User Story:
As a frontend dev, I need to set up the form system JSON schema and UI schema for form 2346 so that content can display on the review page.

## Tasks
- [ ] Create  JSON schema
- [ ] Create UI schema
- [ ] Create PR

## Acceptance Criteria:
- [ ] GH branch is successfully deployed

## Dep/Blockers
