### ISSUE TITLE
Automatically update cypress env vars and viewport presets once a month

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/vets-website#15120]
## Issue Description
Instead of manually logging into the VA.gov Google Analytics account once a month to manually get the latest viewport information for mobile, tablet and desktop devices, then updating the code, and finally submitting a PR, we'd like to automate this process.

---
## Tasks
- [ ] Create a Sidekiq(?) job that executes a script once a month, on the first of every month
- [ ] The script should get the the following data for the mobile, tablet and desktop devices: viewport width and height, percent traffic which uses the viewport
- [ ] Script should update the `config/cypress.json` and `src/platform/testing/e2e/cypress/support/commands/viewportPreset.js` files (or something like that)
- [ ] The script should submit a PR for the updated files (or something like that)

## Acceptance Criteria
- [ ] A new Sidekiq(?) job will be created, along with a script that is executed once a month
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
This was created in the wrong repo - it was in vets-website instead of va.gov-team.

Closing this.
