### ISSUE TITLE
Uvicorn access logs in Grafana

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/vets-website#20837]
## Issue Description

FastAPI/Uvicorn access logs are shipped by Loki into Grafana.
While the raws logs can already bee seen in Grafana Explore,
a dashboard/visualization that to allow search in the log contents
would be next step toward mature Observability. 

---
## Tasks
- [ ] Remove Gunicorn layer on top of Uvicorn for simplification
- [ ] Explore data and parse the fields
- [ ] Produce a Grafana dashboard/visualization that to allow search in the log contents
- [ ] Document the LogQL query to parse the logs

## Acceptance Criteria
- [ ] Grafana ready for demo
---
