### ISSUE TITLE
Create detailed README.md file for COE form app

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/vets-website#21052]
# Background
In order to increase the maintainability for the COE form app we need to create detailed documentation for it. This begins with a very well written README.md file. Please use [the README.md template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/documentation/README_template.md). The README.md file for the COE form app should live in the root of the application folder at `src/applicaitons/lgy/coe/form`

## Tasks
- [ ] Create README.md file from template linked above
- [ ] Fill in all areas of the README.md file
- [ ] Submit a PR for review

## Acceptance criteria
- [ ] The COE form app now has a detailed README.md file

**Comment by Mottie** [comment]
Moved ticket to va.gov-team repo
