### ISSUE TITLE
Add mock data section to View Payments app README.md file

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/vets-website#21053]
# Background
In order to increase the maintainability of the View Payments app by engineers we need to add a section that details how to mock the data for the app. You can get the skeleton for the section from [this template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/documentation/README_template.md). The README.md file for the View Payments app lives in `src/applications/disability-benefits/view-payments`.

## Tasks
- [x] Add mock data section to View Payments README.d file
- [x] Submit a PR for review

## Acceptance criteria
- [x] The View Payments app now has a detailed mock data section
