### ISSUE TITLE
[research] 526 Research Plan Preparation

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/vets-website#21116]
## Value Statement
**_As a_** design researcher **_I want to_** identify pain points and obstacles that a Veteran faces when trying to complete a claim process **_so that_** I can define opportunities and assumptions to test. 

## Research planning hypothesis
We believe that more Veterans will successfully complete disability claims if we can better understand them, their pain points and obstacles Veterans face in the process of applying for disability benefits. We also believe that if we spend more time understanding Veterans over time, we can personalize their experience applying for disability benefits. 

## Goals
Draft a research plan for a longitudinal, multi-method research study to better understand the Veteran experience of applying for disability benefits. 
- Develop a vision and timeline for research plan and conversation guides
- Establish team support and collaboration
- Understand what is enabling us and what might be holding us back from proceeding
- Establish structure and resources to enable research kick-off

## Milestones
- [ ] Draft research goals and plan
- [ ] Develop a recruitment strategy
- [ ] Coordinate with product for quantitative & qualitative synthesis goal alignment
- [ ] Coordinate with VA Design & Research re: methods, recruitment and communication strategy
- [ ] Draft synthesis plan and structure
- [ ] Refine repo taxonomy
- [ ] Draft timeline with recruiting, communications and ideal schedule
- [ ] Coordinate support for survey methods, prototyping, etc.
- [ ] Pre-plan reporting

## Current Status for reference
Form 526 is in production. A Veteran can file for:

Original claim
Claim increase
Benefits Delivery at Discharge (BDD)
There are numerous sub-forms:

Intent to file (Form 20-0966) - automatically filed when 526 is started
PTSD support (Form 781/781a) - for new PTSD submissions
Disclose information to the VA (Form 4142)
Unemployability benefits (Form 8940) - Not yet in production
Employment information (Form 4192) - Not yet in production##
