### ISSUE TITLE
Recruitment Strategy

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/vets-website#21126]
## Value Statement
**_As a_** design researcher **_I want to_** recruit a diverse cohort of Veterans for a research study **_so that_** we can understand a11y issues, pain points and other obstacles to access compensation for disability.   

## Recruitment Strategy and Goals
- Develop a research study that places accessibility, equity and inclusion at the center. 
- Understand what constraints we face in our access to communicating over time with Veterans.
- Establish timeline and communication plans to pre-produce and structure the study.
---

## Open questions
- What constraints to we face in communicating directly with Veterans over time?
- Can this study be replicated with different criteria throughout the contract? How long can we spend with a Veteran cohort to understand their experience over time?
- Can we establish ongoing direct ways of communicating with Veterans in a less formal/interview way?
- Can we conduct micro-surveys?

## Tasks
- [ ] Draft segments to study to get to a maximum equitable state. Prioritize Veterans who face the most obstacles.
- [ ] Define participant group to a small segment for study 1, with plan to replicate in other segments.
- [ ] Coordinate with recruiting resources to gauge viability of ongoing studies (A, B, C research plans in place)
- [ ] Seek learnings from PTSD study approach to replicate trauma-informed practices.
- [ ] Investigate previous diary studies at the VA.
