### ISSUE TITLE
Swap out green buttons for green action links

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/vets-website#21147]
# Background

 https://dsva.slack.com/archives/C01DBGX4P45/p1653064650558229?thread_ts=1653059647.064739&cid=C01DBGX4P45

Design has decided that we should move away from green buttons to start forms and move to using green action links instead. The green action link can be found [here](https://design.va.gov/storybook/?path=/docs/components-action-link--primary) in the design system.

## Tasks
- [ ] Go through each of the forms listed and change any green buttons found to green action links
- [ ] NOD
- [ ] HLR
- [ ] [686c](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/disability-benefits/686c-674)
- [ ] [Chapter 31](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vre/28-1900)
- [ ] [Chapter 36](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/vre/28-8832)
- [ ] 526
- [ ] [COE](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/lgy/coe/form)
- [ ] Submit a PR for review
