### ISSUE TITLE
Certificate of Eligibility | Remove Address Line 3

### ISSUE THREAD

**Issue by scottymeyers** [department-of-veterans-affairs/vets-website#21347]
## Value Statement
**_As an_** Veteran
**_I want to_** only send the values needed to complete a request for a certificate of eligibility 
**_So that_** the LGY service responsible for capturing the request does not receive unnecessary data. 

---
## Background Context
We're currently displaying _Street address line 3_ under _Your contact information_, but the Service isn't anticipating this value, and our API isn't doing anything with it.

@Mottie mentioned that there is a parameter to turn that on and off.

## Acceptance Criteria
- [ ] _The 3rd address line value is removed._ 

## Tasks
- [ ] Turn the parameter off.

## Definition of Ready
- [x] _Clear value description_
- [x] _Testable acceptance criteria_
- [x] _Sample data provided where appropriate_
- [x] _Estimated to fit within the sprint_
- [x] _Dependencies and blockers linked_

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
