### ISSUE TITLE
Update phone number on 526-EZ alert

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/vets-website#22257]
# User Story
As a Veteran I want to make sure that if there is some information that I need to get to the VA regarding my disability claim submission that I can get that information to the correct person.

# Background
On the 526-EZ form we make a check before the Veteran begins the form to make sure we can set up an EDIPI or a BIRLS ID for the Veteran because without one of these they cannot submit a claim. If we are unable to establish one of these we show the Veteran a message that we need more information shown here -

![image (1).png](https://images.zenhubusercontent.com/5d643dbea77bcf04870bc424/878dd8ff-6afc-4a48-b531-7ca93ce2cede)

The phone number shown on this message is incorrect as it routes the Veteran to the general help desk but they are unable to help with an EDIPI or a BIRLS ID.

The correct phone number we need on this error message is 800-698-2411, that is the number for the EVSS help desk.  They are available 24 hours a day, 7 days a week.

## Tasks
- [ ] Update the phone number on the alert
- [ ] Submit a PR for review and merge

## Acceptance criteria
- [ ] The correct phone number now shows on the alert message referenced above
