### ISSUE TITLE
526ez | Figure out what to do with failures outside of our control

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/vets-website#22367]
There are numerous failures that happen daily (<1% of all submissions, but still on the order of hundreds a week) that fail being submitted for form526. These failures, after their 15th attempt/failure, just go into a blackhole. 

They fail for some non-technical reason, outside of our teams control. We have done our job in attempting to submit them (15 times, over a week or so) and there is nothing further we can do with them. We have also made reports in datadog to easily catch and track these and could further improve that process to furnish information on the failures to... _someone_. We need to figure out who that _someone_ is. This ticket is for that. 

An example of some of the failures in downstream systems that we cant do anything to resolve: 

```
<ns4:exception>An error occurred while establishing the claim: Unable to establish claim: GUIE50041&amp;FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!!  FILE: FABTInterfaceCreator.cpp  LINE: 350This update is being elevated for additional review due to an Incident Flash associated with this Beneficiary: - An unexpected error was encountered.  Please contact the System Administrator. Error is: GUIE50041&amp;FABusnsTranRule(CFABUSNS_TRAN) Failed with Exception!!  FILE: FABTInterfaceCreator.cpp  LINE: 350This update is being elevated for additional review due to an Incident Flash associated with this Beneficiary:</ns4:exception>
```

```
<message>No record found for file number XXXXXXX</message>
```

The veteran has no idea that the form they submitted has not actually been submitted and that no further action is going to happen. We need someone to further action these, probably on the VBMS team or at the VA. We don't have the access, knowledge, time, or skills to action these further. 

## Tasks
- [ ] Parse the data from vets api submissions into a csv file to share the other teams
- [x] Define proposed solutions to share with the other teams
- [x] Send weekly list of failures
- [ ] Agree on path forward and write separate tickets for the effort

**Comment by kylesoskin** [comment]
Have some ongoing convos with Emily about this.

**Comment by kylesoskin** [comment]
Have some ongoing convos with VA people about this too, it is progressing but nothing concrete yet.

**Comment by kylesoskin** [comment]
Waiting on input/meetings/discussions from external people.

**Comment by saderagsdale** [comment]
Still waiting for Matthew to reply to Kyle's email from 10/28.

**Comment by kylesoskin** [comment]
@saderagsdale I have a feeling this may be a very slow moving lingering ticket. 

Matthew's response is really just him looking into one individual failure. I am hoping to solve this in a more systematic, general process, type of way. So, I do not think his response is blocking anything like the bigger discussions that need to happen around this (the ones probably with Matt Self and Alejandro and the others on that email).

If we want to manage this in some other way than a ticket that spans many sprints, we may want to do that. Up to you though, I am fine leaving a ticket open to track it, just don't want it to mess up our velocity or sprint metrics or whatever..  if that matters.

**Comment by saderagsdale** [comment]
@kylesoskin my understanding of the email that Matt sent back is that he was looking for an identifier across all of the claims that you shared, not just one participant in particular. In any case, it does warrant a follow-up to diagnose what's happening in a more efficient manner. I'll add it to the agenda for my meeting today with our product owner, and I also send a follow-up email. Hoping to get something scheduled with someone live that can spend time actively looking into this with us.

**Comment by kylesoskin** [comment]
The PDF I sent only had 1 particular claim example in it, and it was my understanding that he was just trying to figure out what the issue is in that 1 particular example of a failure, on his end. 

Regardless, yes, handling ALL the errors, in any manner, is the goal. Since currently they just go into the blackhole and are never seen or heard about again, as far as I know.

**Comment by saderagsdale** [comment]
@kylesoskin Matthew's contact for resolving these has left the VA. Since this is an EVSS thing, is there any reason why Michael Harlow is not the right person to talk to?

**Comment by kylesoskin** [comment]
This is not an EVSS thing. EVSS is just the messenger. This is a VBMS or BGS thing. 

We submit to EVSS, EVSS submit stuff to VBMS and/or BGS, and one of THOSE down-stream services returns an error, to EVSS, who then returns that same error to us. 


US -> EVSS -> VBMS, VBMS Says "Error" -> EVSS -> US

I think we need at a minimum

- a contact at VBMS to look into/resolve TECHNICAL errors, to handle "VBMS system had an error"
- a person that is an end-user/adjunicator/person who can do things IN VBMS to resolve/action cases, to handle "there is an issue with this veterans file, or some other non-technical reason this submission causes an error"

**Comment by kylesoskin** [comment]
Gathering info for VA folks, top priority.

**Comment by saderagsdale** [comment]
@kylesoskin Let me know if this is good to close.
