### ISSUE TITLE
Supplemental Claims | 4142/4142(a) form integration QA and testing

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/vets-website#22414]
## Value Statement

**_As a_** Veteran
**_I want to_** authorize medical providers to disclose my medical records
**_So that_** I can submit those records as evidence to support my claim. 

---
## Background Context
- partner to [#22218](https://github.com/department-of-veterans-affairs/vets-website/issues/22218)
- Forms [4142](https://www.va.gov/find-forms/about-form-21-4142/)/[4124a](https://www.va.gov/find-forms/about-form-21-4142a/) will be submitted with the supplemental claim form, enabling medical providers to disclose records for a claim. 
- Code to do this exists already for form 526ez. The assumption is we can easily reuse that code, and just need some bridge/connectors to those existing classes/methods. 

## Acceptance Criteria
- [ ] QA
- [ ] end to end tests

## Designs and Build Notes
- @thehastingsp 

## Out of scope
- Add here

## Tasks
- [ ] write end to end tests and perform qa/smokes for https://github.com/department-of-veterans-affairs/vets-website/issues/22218

- [x] Copy/paste relevant code chunks
- [x] Confirm it makes a pdf
- [x] Confirm it sends pdf to central mail
- [ ] Confirm this is sufficient

**Comment by sortizsh** [comment]
directly relates to https://github.com/department-of-veterans-affairs/vets-website/issues/22218

**Comment by saderagsdale** [comment]
@sortizsh I combined this with #48408. Going to close this one.
