### ISSUE TITLE
[DDL] Down For Maintenance message

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/vets-website#23221]
## Value Statement
**_As a_** veteran looking for a claim letter
**_I want to_** see some kind of message that lets me know when the service is down
**_So that_**  I'm not surprised when when I go to download a letter and the application just doesn't work

---
## Background Context
Our calls to VBMS are getting a response "DownForMaintenace" on occasion. When this occurs, veterans are unable to download their claim letters. Ideally, when that response is returned, we would have a message that told the veteran the service was down and that they should check back later. The duration of the downtime due to maintenance since launching this service, has been less than an hour each time it has occurred. 

### Related resources
[vbms_connect known errors list](https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/lib/vbms/errors.rb)

## Acceptance Criteria

- [ ] Error message appears to end user only when DownForMaintenance is returned as a value
- [ ] Error message disappears once a different value is returned
- [ ] Error message design meets accessibility guidelines
- [ ] Uses an existing VA.gov component

## Designs and Build Notes
- Add here

## Out of scope
- Add here

## Answered Questions

1. What (if any) is the correlation between the `417` error and the `500` error?
  - There's not always a 417 (Expect error, VBMS::DownForMaintenance) paired with every 500 (Server Error), or even a 417 for a group of 500s, but when there are 417s there are also 500s. There were 121 417 errors within the same timeframe that there were only 30 500 errors.
  - We saw 417s from Jan 8th - 10th, but none after that, but clearly there was a problem from Jan 13th - 15th
2. Does the `DownForMaintenance` error only occur on `#index`? Can it also happen on `#show`?
  - `DownForMaintenance` has been triggered on both `#index` and `#show`
3. Are the `DownForMaintenance` errors and `Internal Server Errors` the only errors that affect the Veteran?
   1. What about those `302: Redirect` errors we saw?
     - It looks like an issue with the redirect because VBA/VBMS was down for maintenance.
   2. Are there more?
     - [vbms_connect known errors list](https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/lib/vbms/errors.rb)
5. Do we care what the difference is between a `DownForMaintenance` and an `Internal Server Error`? 
   1. I care from a technical curiosity perspective, but is there a way we can word the message to be more generic? IE, do we _need_ a "System down for maintenance" message, specifically?
     - A DownForMaintenance error seems more useful than a generic 500 Internal Server Error, because it can be coupled with instructions for a user to return at a later time.
   4. Isn't the message pretty generic now? How can we differentiate? Should we differentiate?
     - As long as we provide actionable instructions ("check back later", or "try x, then try y"), then a veteran probably doesn't care about the specifics.

## Tasks
- [ ] _Task_
- [ ] _Task_
- [ ] _Task_

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
