### ISSUE TITLE
[ Technical Discovery ] CST Content Inventory

### ISSUE THREAD

**Issue by rubensun** [department-of-veterans-affairs/vets-website#24132]
## Value Statement
**Activity ('I want to...')**
Build out a content inventory document mapping CST data values to data values in VBMS / EVSS relating to claims, contentions, and requests (objects, states, attributes)

**Outcome ('So that...')**
The product team has a more grounded understanding of what can feasibly be displayed to users based on current CST functionality, as well as what may be possible in the near term. 

---
## Background Context
Having gained a fuller understanding of user needs, we're needing to conduct additional technical discovery to understand to what extent these needs can be met based on current product functionality, or alternate ways to address needs.

## Acceptance Criteria
- [ ] CST data values captured and mapped to VBMS data values.
- [ ] Fields are accompanied with descriptions to provide clarity surrounding what the values represent

## Designs and Build Notes
(n/a)

## Out of scope
(n/a)

## Tasks
- [x] Review existing technical documentation and create a centralized repository
- [x] Review content with product, engineering, and design.

## Definition of Ready 
- [ x ] Conduct SME interviews to gain an understanding of VBMS data values.

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Reviewed and approved by product, engineering, and design
