### ISSUE TITLE
[bug spike] NOD Unprocessable Entity Investigation

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/vets-website#24502]
## Value Statement

**_As a_** developer
**_I want to_** know the cause of evidence that is too large being allowed to pass through a submission
**_So that_** we can prevent the error from occurring.

---
## Background Context
Time boxed spike (1-2 hours). Look into why the submission was rejected. Looks to be a missing address key issue.

## Tasks
- [ ] Investigate why the submissions is erroring
- [ ] Make tickets to fix it if a large effort (or fix if small effort)

---
## Definition of Ready 
- [x] Gather infomation

## Definition of Done
- [ ] We know the cause of the error
- [ ] We've defined a solution if needed, and assigned it to the appropriate party
- [ ] We've asked the CC team to reach out and ask the Veteran to resubmit

## Additional info/Context
https://vagov.ddog-gov.com/logs?query=%40remote_ip.geoip.ipAddress%3A94.204.229.196%20&cols=host%2Cservice%2C%40payload.error_message&event=AgAAAYiLjDZ1IlM0RgAAAAAAAAAYAAAAAEFZaUxqRHAxQUFCTjlvSm1TT3FYVUFBMwAAACQAAAAAMDE4ODhjMmEtMTIyMS00MzdlLTk3ZTUtNmQ2NTVmOGRiMTU4&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1685954366160&to_ts=1685981677390&live=false

https://vagov.ddog-gov.com/logs?query=%40remote_ip.geoip.ipAddress%3A94.204.229.196%20&cols=host%2Cservice%2C%40payload.error_message&event=AgAAAYiLjDZ1IlM0RwAAAAAAAAAYAAAAAEFZaUxqRHAxQUFCTjlvSm1TT3FYVUFBNAAAACQAAAAAMDE4ODhjMmEtMTIyMS00MzdlLTk3ZTUtNmQ2NTVmOGRiMTU4&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1685954366160&to_ts=1685981677390&live=false

http://sentry.vfs.va.gov/organizations/vsp/issues/198211/?project=3&query=NoticeOfDisagreementsController&statsPeriod=90d
