### ISSUE TITLE
NOD | Update design to match production

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/vets-website#24869]
## Value Statement
**_As a_**  designer
**_I want to_** work off up-to-date design files
**_So that_** we can ensure the starting point for our recommendations is accurate

---
## Acceptance Criteria
- [ ] Design files are reflecting what is currently in production

## Tasks
- [ ] Update design screens to match what's on production for Board Appeal

## Definition of Ready 
- [ ] Clear value description
- [ ] Reviewable acceptance criteria

## Definition of Done
- [ ] AC are met
