### ISSUE TITLE
Determine which JavaScript files can safely be removed from the code base

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2508]
### Task
- Assess whether these scripts are being used on Vets.gov.
- Remove what isn't being used.
- Determine whether jQuery is necessary, and how easy it would be to remove it site-wide. (e.g. menu.js has a jQuery dependency, but could easily be rewritten to use native DOM APIs, with a polyfill for IE8 support)
### Possible candidates for removal

(All found in `assets/js`)
- [ ] `vendor/jquery-1.11.0.min.js`
- [ ] `vendor/classie.js`
- [ ] `vendor/jquery-accessible-simple-tooltip-aria.js`
- [ ] `vendor/jquery.tipsy.js`
- [ ] `vendor/nwmatcher-1.2.5-min.js`
- [ ] `vendor/respond.min.js`
- [ ] `vendor/scroll-settings.js`
- [ ] `vendor/selectivizr-1.0.3b.js`
- [ ] `vendor/stellar-settings.js`
- [ ] `vendor/svg-injector.js`
- [ ] `vendor/tota11y.min.js`
- [x] `vendor/wow.min.js`

**Comment by webinista** [comment]
jQuery is a dependency for the quick search feature of the [GI Bill Comparison Tool](https://www.vets.gov/gi-bill-comparison-tool/)

![screen shot 2016-07-13 at 8 59 21 am](https://cloud.githubusercontent.com/assets/354277/16810275/2cfd331c-48d8-11e6-9dc5-f2b8e324d3f7.png)

**Comment by akainic** [comment]
I think jQuery is also being used for the search button on mobile and/or the Veterans Crisis Line?

**Comment by webinista** [comment]
@akainic It is, but those are relatively easy to rewrite using native DOM APIs.

A typeahead / quick search feature is less easy to rewrite, particularly since we still need to support IE9. And typeahead scripts that do not have a jQuery dependency are somewhat rare. (The only one I know of is Lea Verou's [Awesomeplete](https://leaverou.github.io/awesomplete/).

**Comment by akainic** [comment]
Ah gotcha, I agree it should be easy to rewrite for those 2!

**Comment by webinista** [comment]
We can probably remove Modernizr too, since most of our audience is using modern browsers (i.e. browsers with better CSS/JS support than IE8).

**Comment by webinista** [comment]
Related to #4230, #4444, and #4446

**Comment by webinista** [comment]
We're no longer supporting IE9, so [Awesomeplete](https://leaverou.github.io/awesomplete/) may be viable now for a typeahead feature.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
