### ISSUE TITLE
[CST] - Revise submit language on button

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/vets-website#27555]
## Value Proposition

As a veteran with evidence to submit, I want the language attached to the evidence submission action to make clear to me what part of the claim process I'm initiating when I take that action, so that my expectations around what the VA is going to do with my evidence is clear to me

## Background
As part of our evidence request initiative, we have a new evidence request design that will be applicable on claim detail pages. We need to update the files tab to have this new design.

## Design

Figma mocks
- [Veteran Evidence Requests](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-809&mode=design)
- [3P Evidence Requests](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-1509&mode=design)

Screenshot
<img width="763" alt="Screenshot 2024-01-26 at 1 57 31 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/95102058/2a626650-cc81-4499-b802-6897568884fa">

## Tasks

- [x] Skyler updates mock with the new component
- [x] Skyler updates ticket with new component mock

## Acceptance Criteria

- [x] The 'Add Files' button is renamed to 'Submit files for review' and uses the file-input component
- [x] The 'Need to mail your files?' link is moved around to the bottom of the section so that it's seen as a secondary action to submitting the evidence files.
- [x] Component is updated to use the latest component in the design system for this use case

**Comment by skylerschain** [comment]
@pmclaren19 Updated mocks with new component and updated links/screenshot in the Design section above.

**Comment by HeatherWidmont** [comment]
Spoke with @skylerschain and we created https://github.com/department-of-veterans-affairs/va.gov-team/issues/75136 ticket to handle what the post upload state of a file should look like.

I spoke with the platform design team and there is a multiple prop but it has some bug and ui issues that need to be fixed. Platform team is going to turn off this prop for now for the V3 VAFileInput and work of these issues. We expect these new changes to be release in 2 - 4 weeks and then we can update this with the above ticket.

**Comment by HeatherWidmont** [comment]
@samcoforma to review today after standup

**Comment by HeatherWidmont** [comment]
@jacobworrell to review & close if everything looks good. Yaaaaay thanks Peri & Jacob!

**Comment by jacobworrell** [comment]
@pmclaren19 looks good! Closing.
