### ISSUE TITLE
Incorporate 527EZ Print Form Worksheets Into Digital Form

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/vets-website#30853]
## Background
As a follow on for usability improvements Batch 1 effecting the introduction page and the supporting documents page, the worksheets at the end of the 527EZ paper form are used to collect supporting evidence. Currently they are shown as a simple bullet point on the introduction page, yet never mentioned in the form again. Where should they be displayed within the form?

## Tasks
- [x] Talk to VBA stakeholders to understand how the worksheets are used
- [x] Incorporate into design
- [ ] Show VBA design and language placement on introduction page and supporting documents page
- [ ] Incorporate any feedback
- [ ] Engage CAIA for final content

## Acceptance Criteria
- [ ] Veterans understand when and how to use the worksheets at the end of the 527EZ paper form

**Comment by mtri** [comment]
[Figma design here](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=6378-83238&t=wPk9ygJ7Bd4uJIpS-11)
