### ISSUE TITLE
GrowableTable issues

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3119]
- [ ] The save button doesn't always work on the first try (#3099)
- [ ] Move the 'remove' button out of the inline review (#3032)
- [ ] 'Remove' button should only be visible while editing a record (#3032)
- [ ] If there is only one record, the remove button should not appear in it until there are at least two saved records. (#3032)
- [ ] The add button should not appear below an open record (#3031)
- [ ] The add button should only appear after a record is saved (below the most recent saved record) (#3031)
- [x] How should required fields in an item work? Right now if you have required fields in a list where you don't have to have an item, you have to click remove before moving on.

**Comment by akainic** [comment]
Results from usability testing were extremely negative; doing more usability testing today and then will discuss best implementation of GrowableTable going forward.

**Comment by goldenmeanie** [comment]
Simplified :fingerscrossed: design:

![military-service-tours-start](https://cloud.githubusercontent.com/assets/1969/18928837/dfa2247a-858f-11e6-9175-d17c2ee19cbd.png)
Changes: 
- Remove button is absent from inititial view
- No save button. Continue would submit current contents of form.
- **Add Another Tour** button _see next screen_

![military-service-tours-multiple](https://cloud.githubusercontent.com/assets/1969/18928864/ff5ec9c6-858f-11e6-82e8-3cb02ca1953f.png)
Changes:
- Summary card has a new appearance. (Opportunity for animation to show form turning into card and then spawning anew below)
- **Edit** button only on card. _See next screen_

![military-service-tours-edit](https://cloud.githubusercontent.com/assets/1969/18929021/a0296f32-8590-11e6-9888-0fb6335a51c8.png)
Changes:
- 'Remove' button at the bottom of the form
- 'Update Foo' button closes form again and updates card summary

**Comment by alexose** [comment]
Implementing the simplified design now
