### ISSUE TITLE
Questions for detailed review with Shay

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3210]
- [x] Can a Veteran receive multiple Certificates of Eligibility from one pass through the form, or is multiple selections just s signal that something is wrong? https://github.com/department-of-veterans-affairs/vets-website/issues/3154
  - Processing time issues: #3160
  - Default current relinquishment date to current date: #3155 
- [x] Remove previous claims section: #3161 
   - [x] File numbers and payee numbers
- [x] Service status confusion: #3179 
- [x] How to use the "do not apply this period of service" checkbox? #3238
- [x] Direct deposit: confirm that we are not requiring it
- [x] FAA certificates (what is this field supposed to collect: name, number, etc.?)
- [x] Placement of legal copy: #3156

**Comment by cweber** [comment]
Old questions. Callin' it done.
