### ISSUE TITLE
Modify alert messages to match new style

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#4080]
Updates all alert types to use a modification of `usa-alert` outlined in #4029.

<img width="681" alt="screen shot 2016-11-22 at 10 30 58 am" src="https://cloud.githubusercontent.com/assets/4106356/20536644/a6d4903a-b09e-11e6-8e96-8199dd2b218b.png">

**Claim status:**
- Success
  - [ ] [Upload success](https://marvelapp.com/2dh4dia/screen/15297501)
  - [ ] [Request for decision received](https://marvelapp.com/2dh4dia/screen/15297534)
- Warning
  - [ ] [Tracked items alert](https://marvelapp.com/2dh4dia/screen/15297472)
  - [ ] [Requested of others warning](https://marvelapp.com/2dh4dia/screen/15336880)
  - [ ] [Optional evidence warning](https://marvelapp.com/2dh4dia/screen/15297510)
- Error
  - [ ] [Upload error](https://marvelapp.com/2dh4dia/screen/15300483)
- Informational
  - [ ] [Empty claims list](https://marvelapp.com/2dh4dia/screen/15306428)
  - [ ] [Adding claim details](https://marvelapp.com/2dh4dia/screen/15297473)
  - [ ] [Completed claim](https://marvelapp.com/2dh4dia/screen/15297474)
  - [ ] [Request claim decision](https://marvelapp.com/2dh4dia/screen/15297531)

**Prescriptions:**
- Success
  - [ ] [Refill Requested](https://marvelapp.com/2i284g4/screen/16306309)
- Warning 
  - [ ] [Medication list disclaimer](https://marvelapp.com/2i284g4/screen/16306318)
- Error
  - [ ] [Prescription Refill Unsuccessful](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#3-prescription-refill-unsuccessful)
  - [ ] [Prescription Not Refillable](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#4-prescription-not-refillable)

**Secure messaging:**
- Success
  - [ ] [Sent message](https://marvelapp.com/1bdd199/screen/15044659)
  - [ ] [Deleted draft](https://marvelapp.com/1bdd199/screen/15044660)
  - [ ] [Moved message](https://marvelapp.com/1bdd199/screen/15044690)
  - [ ] [Created a folder](https://marvelapp.com/1bdd199/screen/17079595)
  - [ ] [Deleted a folder](https://marvelapp.com/1bdd199/screen/17079598)
  - [ ] [Deleted a message](https://marvelapp.com/1bdd199/screen/15044660)
  - [ ] [Saved draft](https://marvelapp.com/1bdd199/screen/15044688) 
- Error
  - [ ] [Invalid search](https://marvelapp.com/1bdd199/screen/15055401)
  - [ ] [Triage group errors](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#14-triage-group-errors)
  - [ ] [Unable to move messages](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#15-unable-to-move-message)
  - [ ] [Service errors](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#16-service-errors)
- Informational 
  - [ ] [Things you should know](https://marvelapp.com/1bdd199/screen/15044678)

**Education Benefits:**
- Success
- Warning
  - [ ] [Not all forms are in Vets.gov](https://dev.vets.gov/education/apply-for-education-benefits/)
  - [ ] [Key legalese for relinquishment options](https://dev.vets.gov/education/apply-for-education-benefits/application/benefits-eligibility/benefits-relinquishment)
- Error

- Informational
  - [ ] [Progress saving not available](https://dev.vets.gov/education/apply-for-education-benefits/application/introduction)
  - [ ] [About selection](https://dev.vets.gov/education/apply-for-education-benefits/application/benefits-eligibility/benefits-selection)
  - [ ] [Confirmation details](https://dev.vets.gov/education/apply-for-education-benefits/application/submit-message)

**Health Care Application:**

**Comment by melwoodard** [comment]
@cweber @gnakm @goldenmeanie @angel can you add to the list above any alerts in these apps that should be addressed here?

**Comment by melwoodard** [comment]
@suzchap can you confirm the list of alerts for claim status is correct - nothing missing, nothing here that shouldn't be?

**Comment by cweber** [comment]
I guess my thought is, if we're using common components/css, it doesn't seem like we need to track things down, just make the change. (But I will add our instances of it.)

**Comment by melwoodard** [comment]
Thanks! The hope is that we are already using common components, but this inventory will help us confirm that we are / fix any instances that aren't.

**Comment by suzchap** [comment]
@melwoodard I think you got them all. Thanks!

**Comment by melwoodard** [comment]
Moving this issue to the patterns repo: https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/28
