### ISSUE TITLE
make PR checklist

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4557]

**Comment by akainic** [comment]
- [ ] Description of the change
- [ ] Why it is needed
- [ ] Link to ticket
- [ ] Screenshot of the new version (if there is a UI change)
- [ ] Other parts of the application this might impact (e.g., new field added to front-end that needs to be added to back-end and schema)
- [ ] Other parts of Vets.gov this might impact (e.g., changes to common components)

**Comment by patrickvinograd** [comment]
- [ ] Devops impact - mainly around new configuration parameters, new metrics worth monitoring, etc.

These are certainly good things to keep in mind and communicate in a PR, but I'm a little dubious about checklists and templates like these, insofar as I don't know how often they actually prevent future defects vs. being a reaction to something that happened in the past. I'm not saying don't do it, just be conscientious about whether it becomes burdensome and if so if it's worth the overhead.

**Comment by akainic** [comment]
@patrickvinograd very true. It's something to be conscious of. During our RCA for the recent education bug, we realized that the underlying issue was that the FE and BE teams weren't really talking to each other and weren't aware of what the other was doing. We were hoping that this would be one fix for that problem. I think in general it's a good practice to document PRs thoroughly so others can understand what you did and why. If this becomes too burdensome, though, we can certainly revisit.
